"""SoDex REST client — EIP-712 typed signing per latest spec.

Single Responsibility: produce wire-correct signed requests against
SoDex's spot/perps gateways, plus thin read-only helpers. No business
rules (caps, daily-limits) — those live in callers.

Key spec gotchas this module gets right (see
https://sodex.com/documentation/trading-api/trading-api):

  1. `X-API-Key` header carries the **API-key NAME string** (e.g.
     "kinetic-bot-01"), NOT an EVM address.
  2. `payloadHash = keccak256(json.Marshal({"type": "<action>",
     "params": {...}}))` — full envelope, compact JSON, struct-field
     order preserved (Python 3.7+ dict insertion order; we always
     define payload literals in the order the SoDex Go structs
     declare).
  3. Casing: `accountID`, `symbolID` (uppercase ID).
  4. DecimalString fields (`price`, `quantity`, `funds`, `stopPrice`)
     are JSON strings; enum/int fields (`side`, `type`, `timeInForce`,
     `modifier`, `stopType`, `triggerType`, `positionSide`) are ints;
     `omitempty` fields must be absent when unset.
  5. Domain: spot uses `name="spot"`, perps uses `name="futures"`.
     Testnet `chainId=138565`; mainnet `chainId=286623`.
  6. Typed signature = `0x01` || sig (65 bytes).
  7. Nonce = unix-ms within `(T-2d, T+1d)`, per signing-address.
  8. All outbound HTTP routes through `app.http_client`
     (`service="sodex"`) so the per-service circuit breaker is shared.
"""
from __future__ import annotations

import json
import logging
import time
from typing import Any, Optional

from eth_account import Account
from web3 import Web3

from app import http_client
from app.config import get_settings

logger = logging.getLogger(__name__)

# 10 popular trading assets curated for the trading-signal card mode.
# All 10 have cards generated by `trading_signal_engine`. Only the
# subset present in `SODEX_SYMBOL_IDS` is executable on SoDex testnet
# right now — others raise a clean `symbol_not_listed_on_sodex` error
# at execute time, so users still get the prediction card but no order.
TARGET_ASSETS: tuple[str, ...] = (
    "BTC", "ETH", "SOL", "AVAX", "SUI", "ARB", "OP", "LINK", "INIT", "ATOM",
)

# SoDex testnet perps symbol IDs (fetched from /markets/symbols, 2026-06-02).
# `newOrder` requires `symbolID` as an integer per the Go SDK PerpsOrderItem
# struct — passing a string fails server-side signature verification.
SODEX_SYMBOL_IDS: dict[str, int] = {
    "BTC":  1,
    "ETH":  2,
    "LINK": 3,
    "SOL":  4,
    "SUI":  18,
    "AVAX": 20,
    # ARB / OP / INIT / ATOM not yet listed on SoDex testnet — execute will
    # 422 with `symbol_not_listed_on_sodex` until they are.
}

# Per-symbol order constraints (testnet, snapshot 2026-06-02).
# `quantity_precision` = max digits after decimal point in the qty string.
# `step_size` = the qty must be a multiple of this. `min_notional` = USD.
# Sending `0.000373` for BTC (qtyPrec=5) fails because that's 6 fractional
# digits; rounding to 5 digits → `0.00037`. Sending `0.3237` for SOL
# (qtyPrec=3) fails likewise; rounded → `0.324`.
SODEX_QTY_RULES: dict[str, dict[str, float | int]] = {
    "BTC":  {"precision": 5, "step": 0.00001, "min_qty": 0.00001, "min_notional": 10},
    "ETH":  {"precision": 4, "step": 0.0001,  "min_qty": 0.0001,  "min_notional": 10},
    "LINK": {"precision": 1, "step": 0.1,     "min_qty": 0.1,     "min_notional": 10},
    "SOL":  {"precision": 3, "step": 0.001,   "min_qty": 0.001,   "min_notional": 10},
    "SUI":  {"precision": 1, "step": 0.1,     "min_qty": 0.1,     "min_notional": 10},
    "AVAX": {"precision": 0, "step": 1,       "min_qty": 1,       "min_notional": 10},
}


def format_quantity(symbol: str, raw_qty: float) -> Optional[str]:
    """Snap `raw_qty` to the symbol's step size, format to its precision.
    Returns None if the result would be below `min_qty` (caller raises).
    """
    rules = SODEX_QTY_RULES.get(symbol.upper())
    if not rules:
        return None
    step = float(rules["step"])
    min_qty = float(rules["min_qty"])
    snapped = round(raw_qty / step) * step
    if snapped < min_qty:
        return None
    prec = int(rules["precision"])
    s = f"{snapped:.{prec}f}"
    # Trim trailing zeros only if precision allows fractional digits;
    # for whole-unit pairs (AVAX prec=0) keep the integer form.
    if prec > 0:
        s = s.rstrip("0").rstrip(".") or "0"
    return s


def to_sodex_symbol_id(symbol: str) -> Optional[int]:
    sym = symbol.upper().split("/")[0]
    return SODEX_SYMBOL_IDS.get(sym)


def to_sodex_symbol(symbol: str) -> Optional[str]:
    """Backward-compat helper — returns the canonical pair name string
    (e.g. `BTC-USD`) or None. The integer ID is the authoritative key
    for trading; this is for display/logging only.
    """
    sym = symbol.upper().split("/")[0]
    return f"{sym}-USD" if sym in SODEX_SYMBOL_IDS else None


# ── Order-shape constants (perps) ───────────────────────────────────────
# Match SoDex Go SDK enum values. Kept here as named constants so callers
# never pass magic numbers into payloads.
SIDE_BUY, SIDE_SELL = 1, 2
TYPE_LIMIT, TYPE_MARKET = 1, 2
TIF_GTC, TIF_FOK, TIF_IOC = 1, 2, 3
# SoDex `positionSide`: in BOTH (one-way) mode the only accepted value is
# `1`. In hedge mode `1=LONG / 2=SHORT`. Our master account is in BOTH
# mode, so default everywhere to 1 — `side` controls direction.
POS_LONG, POS_SHORT = 1, 1


class SoDexClient:
    def __init__(self) -> None:
        s = get_settings()
        self._key_name: str = s.sodex_api_key_name or "default"
        self._key_priv: str = s.sodex_api_key_privkey or s.sodex_private_key
        self._chain_id: int = int(s.sodex_chain_id)
        self._account_id: str = s.sodex_account_id
        self._is_mainnet = self._chain_id == 286623
        host = "mainnet-gw.sodex.dev" if self._is_mainnet else "testnet-gw.sodex.dev"
        self._spot_base = f"https://{host}/api/v1/spot"
        self._perps_base = f"https://{host}/api/v1/perps"
        self._acct = Account.from_key(self._key_priv) if self._key_priv else None

    # ── Signing primitives ──────────────────────────────────────────────
    def _domain(self, *, perps: bool) -> dict[str, Any]:
        return {
            "name": "futures" if perps else "spot",
            "version": "1",
            "chainId": self._chain_id,
            "verifyingContract": "0x0000000000000000000000000000000000000000",
        }

    @staticmethod
    def _payload_hash(action: str, params: dict[str, Any]) -> bytes:
        """keccak256 of compact `{type, params}` JSON.

        Python 3.7+ preserves insertion order, so as long as caller builds
        `params` in struct-field order, json.dumps produces a byte string
        identical to Go's json.Marshal output. Crucial: no spaces, no
        sorted keys, no NaN/Infinity.
        """
        envelope = {"type": action, "params": params}
        body = json.dumps(envelope, separators=(",", ":"), allow_nan=False)
        return Web3.keccak(text=body)

    def _sign(self, action: str, params: dict[str, Any], *, perps: bool) -> tuple[str, int]:
        if not self._acct:
            raise RuntimeError("sodex: no signing key configured")
        nonce_ms = int(time.time() * 1000)
        full = {
            "types": {
                "EIP712Domain": [
                    {"name": "name", "type": "string"},
                    {"name": "version", "type": "string"},
                    {"name": "chainId", "type": "uint256"},
                    {"name": "verifyingContract", "type": "address"},
                ],
                "ExchangeAction": [
                    {"name": "payloadHash", "type": "bytes32"},
                    {"name": "nonce", "type": "uint64"},
                ],
            },
            "primaryType": "ExchangeAction",
            "domain": self._domain(perps=perps),
            "message": {
                "payloadHash": self._payload_hash(action, params),
                "nonce": nonce_ms,
            },
        }
        signed = Account.sign_typed_data(self._key_priv, full_message=full)
        # SoDex expects the recovery byte normalised to {0, 1}, not {27, 28}.
        # eth_account emits 27/28 by default; subtract 27 before prefixing
        # the typed-signature byte 0x01.
        sig_bytes = signed.signature
        v_raw = sig_bytes[-1]
        v_norm = v_raw - 27 if v_raw >= 27 else v_raw
        sig_norm = sig_bytes[:-1] + bytes([v_norm])
        return "0x01" + sig_norm.hex(), nonce_ms

    def _signed_headers(self, action: str, params: dict[str, Any], *, perps: bool) -> dict[str, str]:
        sig, nonce = self._sign(action, params, perps=perps)
        return {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "X-API-Key": self._key_name,
            "X-API-Sign": sig,
            "X-API-Nonce": str(nonce),
        }

    # ── Read helpers (public, no signing) ───────────────────────────────
    def _get(self, base: str, path: str, params: Optional[dict] = None) -> Optional[dict]:
        r = http_client.get(f"{base}{path}", service="sodex",
                            params=params, headers={"Accept": "application/json"})
        return r.json() if r else None

    def get_perps_symbols(self) -> Optional[dict]:
        return self._get(self._perps_base, "/markets/symbols")

    def get_perps_ticker(self, symbol: str) -> Optional[dict]:
        return self._get(self._perps_base, f"/markets/{symbol}/ticker")

    def get_account_state(self, address: str) -> Optional[dict]:
        return self._get(self._perps_base, f"/accounts/{address}/state")

    def get_master_account_state(self) -> Optional[dict]:
        """Account state for the API-key signing address (the master/bot
        account that actually holds the testnet vUSDC). This is the ONLY
        correct caller for SoDex's `/accounts/{address}/state` in this
        codebase — never pass a user wallet address here.
        """
        if not self._acct:
            return None
        return self.get_account_state(self._acct.address)

    # 60-second in-process cache for fills lookups. Keyed by order_id
    # because SoDex's `/accounts/{addr}/trades?orderID=` is the
    # authoritative fills source — a single order rarely picks up new
    # fills after IOC market orders complete (~seconds), so 60s TTL is
    # safe and keeps Portfolio/History page loads cheap.
    _fills_cache: dict[int, tuple[float, list[dict[str, Any]]]] = {}
    _FILLS_TTL = 60.0

    def fetch_fills_for_order(self, order_id: int) -> list[dict[str, Any]]:
        """Return the live fills for one SoDex perps order id. Empty
        list on failure (graceful degrade — never raises).

        Output rows are pruned to the public-safe fields callers need
        (price, qty, fee, ts, side); raw SoDex schema fields are dropped
        to keep the payload tight on the wire.
        """
        if not order_id or not self._acct:
            return []
        now = time.time()
        cached = self._fills_cache.get(int(order_id))
        if cached and (now - cached[0] < self._FILLS_TTL):
            return cached[1]

        try:
            data = self._get(self._perps_base,
                             f"/accounts/{self._acct.address}/trades",
                             params={"orderID": int(order_id), "limit": 100})
        except Exception as e:
            logger.debug("sodex fetch_fills_for_order(%s) failed: %s", order_id, e)
            data = None

        rows: list[dict[str, Any]] = []
        if isinstance(data, dict) and isinstance(data.get("data"), list):
            for r in data["data"]:
                if not isinstance(r, dict):
                    continue
                rows.append({
                    "price": str(r.get("price") or r.get("execPrice") or ""),
                    "qty":   str(r.get("quantity") or r.get("qty") or ""),
                    "fee":   str(r.get("fee") or r.get("commission") or "0"),
                    "ts":    int(r.get("timestamp") or r.get("ts") or 0),
                    "side":  "buy" if int(r.get("side") or 0) == SIDE_BUY else "sell",
                })

        self._fills_cache[int(order_id)] = (now, rows)
        return rows

    # ── Write helpers (signed) ──────────────────────────────────────────
    def _signed_post(self, base: str, path: str, action: str,
                     params: dict[str, Any], *, perps: bool) -> Optional[dict]:
        if not self._acct:
            logger.error("sodex: signing key not configured; refusing to send %s", action)
            return None
        # HTTP body is the params object (without the {type} wrapper).
        body_json = json.dumps(params, separators=(",", ":"), allow_nan=False)
        headers = self._signed_headers(action, params, perps=perps)
        r = http_client.post(f"{base}{path}", service="sodex",
                             content=body_json, headers=headers)
        return r.json() if r else None

    def place_perps_order(self, *,
                          account_id: int,
                          symbol_id: int,
                          side: int,
                          quantity: str,
                          price: str = "0",
                          time_in_force: int = TIF_IOC,
                          order_type: int = TYPE_MARKET,
                          position_side: int = POS_LONG,
                          cl_ord_id: Optional[str] = None) -> Optional[dict]:
        """Place a single perps order. Caller is responsible for:
          - converting USD notional → quantity (we don't read mark here)
          - enforcing risk caps (notional/leverage/symbol)
        Returns the SoDex `data` payload or None on failure.
        """
        # Field order MUST match Go struct PerpsOrderItem. omitempty
        # fields (`price`, `funds`, `stopPrice`, `stopType`, `triggerType`)
        # MUST be absent when unset — including them with zero values
        # causes server-side `*_invalid` rejections.
        order = {
            "clOrdID": cl_ord_id or f"kn_{int(time.time()*1000)}",
            "modifier": 1,
            "side": int(side),
            "type": int(order_type),
            "timeInForce": int(time_in_force),
            "quantity": quantity,
            "reduceOnly": False,
            "positionSide": int(position_side),
        }
        if order_type == TYPE_LIMIT and price not in (None, "0", ""):
            # Limit orders need a price; market orders must not.
            order["price"] = price
        params = {
            "accountID": int(account_id),
            "symbolID": int(symbol_id),
            "orders": [order],
        }
        return self._signed_post(self._perps_base, "/trade/orders",
                                 "newOrder", params, perps=True)

    def update_leverage(self, account_id: int, symbol_id: int, leverage: int) -> Optional[dict]:
        params = {
            "accountID": int(account_id),
            "symbolID": int(symbol_id),
            "leverage": int(leverage),
        }
        return self._signed_post(self._perps_base, "/trade/leverage",
                                 "updateLeverage", params, perps=True)

    def cancel_perps_order(self, account_id: int, cl_ord_id: str) -> Optional[dict]:
        params = {
            "accountID": int(account_id),
            "clOrdIDs": [cl_ord_id],
        }
        return self._signed_post(self._perps_base, "/trade/orders/cancel",
                                 "cancelOrder", params, perps=True)


# ── Module-level lazy singleton ─────────────────────────────────────────
_client: Optional[SoDexClient] = None


def get_sodex_client() -> Optional[SoDexClient]:
    """Return the shared client; None if SoDex is disabled in settings."""
    global _client
    s = get_settings()
    if not s.sodex_enabled:
        return None
    if _client is None:
        _client = SoDexClient()
    return _client
